# Per-app deploy root for target-app: pr-diff-summarizer (generated by devops-agent).
# Deploy with: .\scripts\deploy-target-app.ps1 -Feature pr-diff-summarizer

terraform {
  required_version = ">= 1.10"

  backend "s3" {
    bucket       = "sdlc-tfstate-061836593297-us-east-2"
    key          = "dev/apps/pr-diff-summarizer/terraform.tfstate"
    region       = "us-east-2"
    use_lockfile = true
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"

  default_tags {
    tags = {
      Project     = "sdlc-agentic-ai-platform"
      Environment = "dev"
      TargetApp   = "pr-diff-summarizer"
      ManagedBy   = "terraform"
    }
  }
}

data "terraform_remote_state" "shared" {
  backend = "s3"
  config = {
    bucket = "sdlc-tfstate-061836593297-us-east-2"
    key    = "dev/_shared/terraform.tfstate"
    region = "us-east-2"
  }
}

module "app" {
  source = "../../../modules/target-app-ecs"

  app_name    = "pr-diff-summarizer"
  environment = "dev"
  aws_region  = "us-east-2"

  vpc_id                = data.terraform_remote_state.shared.outputs.vpc_id
  subnet_ids            = data.terraform_remote_state.shared.outputs.public_subnet_ids
  cluster_arn           = data.terraform_remote_state.shared.outputs.cluster_arn
  alb_listener_arn      = data.terraform_remote_state.shared.outputs.alb_listener_arn
  alb_security_group_id = data.terraform_remote_state.shared.outputs.alb_security_group_id

  enable_ui      = true
  enable_bedrock = true
  extra_env = {
    API_KEY = "9srDL4WNvHonpY6_i75V7VbdMT9VfhKK"
  }
  has_database         = true
  db_secret_arn        = aws_secretsmanager_secret.db.arn
  db_security_group_id = data.aws_db_instance.rds.vpc_security_groups[0]
}

variable "database_url" {
  description = "SQLAlchemy Postgres DSN — supplied by deploy script via TF_VAR_database_url."
  type        = string
  sensitive   = true
}

resource "aws_secretsmanager_secret" "db" {
  name                    = "sdlc/pr-diff-summarizer/database-url"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db" {
  secret_id     = aws_secretsmanager_secret.db.id
  secret_string = var.database_url
}

data "aws_db_instance" "rds" {
  db_instance_identifier = "agenticaidbinstance"
}

output "app_url" {
  value = "http://${data.terraform_remote_state.shared.outputs.alb_dns_name}/pr-diff-summarizer/"
}

output "ecr_repository_api" {
  value = module.app.ecr_repository_api
}

output "ecr_repository_ui" {
  value = module.app.ecr_repository_ui
}

output "service_name" {
  value = module.app.service_name
}

output "cluster_name" {
  value = data.terraform_remote_state.shared.outputs.cluster_name
}
