# Per-app deploy root for target-app: hello-fastapi (generated by devops-agent).
# Deploy with: .\scripts\deploy-target-app.ps1 -Feature hello-fastapi

terraform {
  required_version = ">= 1.10"

  backend "s3" {
    bucket       = "sdlc-tfstate-061836593297-us-east-2"
    key          = "dev/apps/hello-fastapi/terraform.tfstate"
    region       = "us-east-2"
    use_lockfile = true
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
  }
}

provider "aws" {
  region = "us-east-2"

  default_tags {
    tags = {
      Project     = "sdlc-agentic-ai-platform"
      Environment = "dev"
      TargetApp   = "hello-fastapi"
      ManagedBy   = "terraform"
    }
  }
}

data "terraform_remote_state" "shared" {
  backend = "s3"
  config = {
    bucket = "sdlc-tfstate-061836593297-us-east-2"
    key    = "dev/_shared/terraform.tfstate"
    region = "us-east-2"
  }
}

module "app" {
  source = "../../../modules/target-app-ecs"

  app_name    = "hello-fastapi"
  environment = "dev"
  aws_region  = "us-east-2"

  vpc_id                = data.terraform_remote_state.shared.outputs.vpc_id
  subnet_ids            = data.terraform_remote_state.shared.outputs.public_subnet_ids
  cluster_arn           = data.terraform_remote_state.shared.outputs.cluster_arn
  alb_listener_arn      = data.terraform_remote_state.shared.outputs.alb_listener_arn
  alb_security_group_id = data.terraform_remote_state.shared.outputs.alb_security_group_id

  enable_ui     = true
  db_secret_arn = null # no database for this app
}

output "app_url" {
  value = "http://${data.terraform_remote_state.shared.outputs.alb_dns_name}/hello-fastapi/"
}

output "ecr_repository_api" {
  value = module.app.ecr_repository_api
}

output "ecr_repository_ui" {
  value = module.app.ecr_repository_ui
}

output "service_name" {
  value = module.app.service_name
}

output "cluster_name" {
  value = data.terraform_remote_state.shared.outputs.cluster_name
}
