"""DevOps agent — Strands + Bedrock; Terraform deploy roots and AWS target-app deploy."""

from __future__ import annotations

import argparse
import json
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

for _stream in (sys.stdout, sys.stderr):
    if hasattr(_stream, "reconfigure"):
        _stream.reconfigure(encoding="utf-8", errors="replace")

_REPO_ROOT = Path(__file__).resolve().parents[2]
_INFRA_DIR = _REPO_ROOT / "infrastructure"
_PIPELINE_DIR = _REPO_ROOT / "agents" / "pipeline"

sys.path.insert(0, str(_REPO_ROOT / "agents"))
from _shared.artifact_store import is_s3_store, put_handoff, resolve_run_id, update_pipeline_run
from _shared.context_cli import load_context_extra, parse_context_args
from _shared.deploy_manifest import (
    build_deploy_manifest,
    database_url_from_env,
    ensure_deploy_dockerfiles,
)
from _shared.env import load_repo_env
from _shared.pipeline_context import (
    TargetAppRequiredError,
    enrich_handoff_context,
    resolve_cli_context,
    resolve_target_app,
)

load_repo_env()
os.environ.setdefault("BYPASS_TOOL_CONSENT", "true")

import botocore.config
from a2a.types import AgentSkill
from strands import Agent
from strands.models import BedrockModel
from strands.multiagent.a2a import A2AServer
from strands.tools.decorator import tool

AGENT_NAME = "devops-agent"
A2A_PORT = 9105


def _pipeline_run_marker_candidates(target: str) -> list[Path]:
    """Locations gitlab-agent may write ``.sdlc/pipeline-run.json``.

    Monorepo / platform CI: ``target-apps/<slug>/.sdlc/…``
    Apps-repo publish (branch root = app tree) overlaid onto ``backend/``: ``.sdlc/…``
    """
    slug = (target or "").strip()
    return [
        _REPO_ROOT / "target-apps" / slug / ".sdlc" / "pipeline-run.json",
        _REPO_ROOT / ".sdlc" / "pipeline-run.json",
    ]


def _ensure_pipeline_run_id_from_marker(target: str, ctx: dict[str, Any]) -> None:
    """If PIPELINE_RUN_ID is unset, load it from the gitlab-agent publish marker."""
    if resolve_run_id(ctx):
        return
    for marker in _pipeline_run_marker_candidates(target):
        if not marker.is_file():
            continue
        try:
            data = json.loads(marker.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        rid = str(data.get("runId") or "").strip()
        if not rid:
            continue
        os.environ["PIPELINE_RUN_ID"] = rid
        ctx["runId"] = rid
        try:
            rel = marker.relative_to(_REPO_ROOT).as_posix()
        except ValueError:
            rel = str(marker)
        print(f"[{AGENT_NAME}] Loaded PIPELINE_RUN_ID from {rel}")
        return


_WINGET_TF_DIR = (
    Path.home()
    / "AppData/Local/Microsoft/WinGet/Packages"
    / "Hashicorp.Terraform_Microsoft.Winget.Source_8wekyb3d8bbwe"
)

_TF_ROOT_TEMPLATE = '''\
# Per-app deploy root for target-app: {app} (generated by devops-agent).
# Deploy with: .\\scripts\\deploy-target-app.ps1 -Feature {app}

terraform {{
  required_version = ">= 1.10"

  backend "s3" {{
    bucket       = "sdlc-tfstate-061836593297-us-east-2"
    key          = "dev/apps/{app}/terraform.tfstate"
    region       = "us-east-2"
    use_lockfile = true
  }}

  required_providers {{
    aws = {{
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }}
  }}
}}

provider "aws" {{
  region = "us-east-2"

  default_tags {{
    tags = {{
      Project     = "sdlc-agentic-ai-platform"
      Environment = "dev"
      TargetApp   = "{app}"
      ManagedBy   = "terraform"
    }}
  }}
}}

data "terraform_remote_state" "shared" {{
  backend = "s3"
  config = {{
    bucket = "sdlc-tfstate-061836593297-us-east-2"
    key    = "dev/_shared/terraform.tfstate"
    region = "us-east-2"
  }}
}}

module "app" {{
  source = "../../../modules/target-app-ecs"

  app_name    = "{app}"
  environment = "dev"
  aws_region  = "us-east-2"

  vpc_id                = data.terraform_remote_state.shared.outputs.vpc_id
  subnet_ids            = data.terraform_remote_state.shared.outputs.public_subnet_ids
  cluster_arn           = data.terraform_remote_state.shared.outputs.cluster_arn
  alb_listener_arn      = data.terraform_remote_state.shared.outputs.alb_listener_arn
  alb_security_group_id = data.terraform_remote_state.shared.outputs.alb_security_group_id

  enable_ui      = {enable_ui}
  enable_bedrock = {enable_bedrock}
{extra_env_block}{db_module_inputs}}}

{db_resources}output "app_url" {{
  value = "http://${{data.terraform_remote_state.shared.outputs.alb_dns_name}}/{app}/"
}}

output "ecr_repository_api" {{
  value = module.app.ecr_repository_api
}}

output "ecr_repository_ui" {{
  value = module.app.ecr_repository_ui
}}

output "service_name" {{
  value = module.app.service_name
}}

output "cluster_name" {{
  value = data.terraform_remote_state.shared.outputs.cluster_name
}}
'''

_DB_MODULE_INPUTS_NONE = "  db_secret_arn = null # no database for this app\n"

_DB_MODULE_INPUTS = """\
  has_database         = true
  db_secret_arn        = aws_secretsmanager_secret.db.arn
  db_security_group_id = {db_sg_expr}
"""

_DB_RESOURCES = """\
variable "database_url" {{
  description = "SQLAlchemy Postgres DSN — supplied by deploy script via TF_VAR_database_url."
  type        = string
  sensitive   = true
}}

resource "aws_secretsmanager_secret" "db" {{
  name                    = "sdlc/{app}/database-url"
  recovery_window_in_days = 0
}}

resource "aws_secretsmanager_secret_version" "db" {{
  secret_id     = aws_secretsmanager_secret.db.id
  secret_string = var.database_url
}}

{db_instance_data}
"""

_DB_INSTANCE_DATA = """\
data "aws_db_instance" "rds" {{
  db_instance_identifier = "{db_instance}"
}}
"""

DEVOPS_SYS_PROMPT = """\
You are the DevOps Agent for the SDLC Agentic AI Platform.

## Job
Author the per-app Terraform deploy root `infrastructure/environments/dev/<app>/main.tf`
for the target app in the deploy manifest, then validate it. The root calls the
reusable module `infrastructure/modules/target-app-ecs` (ECS Fargate + shared ALB,
app served at http://<alb>/<app>/).

## Hard rules
- Write ONLY under `infrastructure/environments/dev/<targetApp>/` via devops_write_tf.
- NEVER modify `infrastructure/modules/`, `environments/dev/_shared/`, `bootstrap/`,
  or any target-app code.
- NEVER run terraform apply/destroy — the deploy script owns that.
- Follow the CANONICAL TEMPLATE in the task message exactly; only the marked
  app-shape inputs may vary (enable_ui, DB block). Keep the S3 backend block and
  remote-state wiring byte-identical apart from the app slug.
- Use the terraform MCP tools (search/get provider or module docs) ONLY if you must
  deviate from the template (e.g. an extra AWS resource the manifest demands).
- GitLab publish is gitlab-agent's job; do not push code or open MRs.

## Workflow
1. Read the deploy manifest in the task message (it is ground truth — do not
   re-derive app shape yourself).
2. If the manifest says tfRootExists=true, read the existing main.tf first with
   devops_read_file and keep it unless it conflicts with the manifest.
3. Write main.tf with devops_write_tf.
4. Call devops_validate. If it fails, fix and re-validate (max 3 attempts).
5. Reply with a short summary: files written, validation result, and the module
   inputs chosen (enable_ui, db wiring) with one-line reasons tied to the manifest.
"""


def _bedrock_model() -> BedrockModel:
    model_id = os.getenv("MODEL_ID", "us.anthropic.claude-sonnet-4-20250514-v1:0")
    return BedrockModel(
        model_id=model_id,
        region_name=os.getenv("AWS_REGION", "us-east-2"),
        max_tokens=int(os.getenv("DEVOPS_AGENT_MAX_TOKENS", "8192")),
        streaming=True,
        boto_client_config=botocore.config.Config(
            read_timeout=int(os.getenv("BEDROCK_READ_TIMEOUT", "600")),
            connect_timeout=10,
            retries={"mode": "standard", "max_attempts": 2},
        ),
    )


def _terraform_exe() -> str:
    exe = shutil.which("terraform")
    if exe:
        return exe
    candidate = _WINGET_TF_DIR / "terraform.exe"
    if candidate.is_file():
        return str(candidate)
    raise FileNotFoundError(
        "terraform not found on PATH. Install with: winget install HashiCorp.Terraform"
    )


def _tf_root(app: str) -> Path:
    return _INFRA_DIR / "environments" / "dev" / app


_SLUG_RE = re.compile(r"^[a-z][a-z0-9-]{1,40}$")


def _check_app_slug(app: str) -> str | None:
    if not _SLUG_RE.match(app):
        return f"Invalid app slug '{app}' (lowercase kebab-case required)."
    return None


# ── Agent tools (scoped) ───────────────────────────────────────────────────────
@tool
def devops_read_file(path: str) -> str:
    """Read a repo file. Allowed: infrastructure/**, target-apps/<app>/**, agents/pipeline/*.json."""
    rel = path.replace("\\", "/").lstrip("/")
    allowed = rel.startswith(("infrastructure/", "target-apps/", "agents/pipeline/"))
    if not allowed or ".." in rel:
        return f"ERROR: path not allowed: {rel}"
    full = _REPO_ROOT / rel
    if not full.is_file():
        return f"ERROR: not a file: {rel}"
    try:
        return full.read_text(encoding="utf-8")
    except OSError as exc:
        return f"ERROR: {exc}"


@tool
def devops_write_tf(app: str, filename: str, content: str) -> str:
    """Write a .tf file into infrastructure/environments/dev/<app>/ (creates the dir)."""
    err = _check_app_slug(app)
    if err:
        return f"ERROR: {err}"
    if not filename.endswith(".tf") or "/" in filename or "\\" in filename or ".." in filename:
        return "ERROR: filename must be a bare *.tf name (e.g. main.tf)."
    root = _tf_root(app)
    root.mkdir(parents=True, exist_ok=True)
    (root / filename).write_text(content, encoding="utf-8", newline="\n")
    return f"WROTE infrastructure/environments/dev/{app}/{filename} ({len(content)} chars)"


@tool
def devops_validate(app: str) -> str:
    """Run `terraform init -backend=false` + `terraform validate` in the app's TF root."""
    err = _check_app_slug(app)
    if err:
        return f"ERROR: {err}"
    root = _tf_root(app)
    if not (root / "main.tf").is_file():
        return f"ERROR: no main.tf in infrastructure/environments/dev/{app}/"
    try:
        tf = _terraform_exe()
    except FileNotFoundError as exc:
        return f"ERROR: {exc}"

    # Shared provider cache: avoids re-downloading the AWS provider every init.
    if not os.environ.get("TF_PLUGIN_CACHE_DIR"):
        cache = Path(os.environ.get("LOCALAPPDATA", str(Path.home()))) / "terraform-plugin-cache"
        cache.mkdir(parents=True, exist_ok=True)
        os.environ["TF_PLUGIN_CACHE_DIR"] = str(cache)

    outputs: list[str] = []
    for args in (["init", "-backend=false", "-input=false"], ["validate", "-no-color"]):
        proc = subprocess.run(
            [tf, *args],
            cwd=root,
            capture_output=True,
            text=True,
            timeout=300,
        )
        tail = (proc.stdout + proc.stderr)[-2000:]
        outputs.append(f"$ terraform {' '.join(args)} (exit {proc.returncode})\n{tail}")
        if proc.returncode != 0:
            return "FAILED\n" + "\n".join(outputs)

    # Leave no half-initialized workspace behind; the deploy script re-inits with
    # the real S3 backend and a stale backend-less .terraform/ breaks that.
    shutil.rmtree(root / ".terraform", ignore_errors=True)
    return "VALIDATION OK\n" + "\n".join(outputs)


# ── Terraform generation helpers ───────────────────────────────────────────────
def render_tf_root(manifest: dict[str, Any]) -> str:
    """Render the canonical per-app main.tf from the deploy manifest (no LLM needed)."""
    app = manifest["targetApp"]
    if manifest.get("hasDatabase"):
        db_instance = manifest.get("dbInstanceIdentifier")
        db_sg_expr = (
            "data.aws_db_instance.rds.vpc_security_groups[0]" if db_instance else "null"
        )
        db_module_inputs = _DB_MODULE_INPUTS.format(db_sg_expr=db_sg_expr)
        db_instance_data = (
            _DB_INSTANCE_DATA.format(db_instance=db_instance) if db_instance else ""
        )
        db_resources = _DB_RESOURCES.format(app=app, db_instance_data=db_instance_data)
    else:
        db_module_inputs = _DB_MODULE_INPUTS_NONE
        db_resources = ""

    extra_env = manifest.get("extraEnv") or {}
    if extra_env:
        def _hcl_str(value: str) -> str:
            return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

        lines = "\n".join(f"    {k} = {_hcl_str(str(v))}" for k, v in sorted(extra_env.items()))
        extra_env_block = f"  extra_env = {{\n{lines}\n  }}\n"
    else:
        extra_env_block = ""

    return _TF_ROOT_TEMPLATE.format(
        app=app,
        enable_ui="true" if manifest.get("enableUi") else "false",
        enable_bedrock="true" if manifest.get("usesBedrock") else "false",
        extra_env_block=extra_env_block,
        db_module_inputs=db_module_inputs,
        db_resources=db_resources,
    )


def _merge_handoff(app: str, updates: dict[str, Any]) -> Path:
    _PIPELINE_DIR.mkdir(parents=True, exist_ok=True)
    path = _PIPELINE_DIR / f"{app}.devops-handoff.json"
    data: dict[str, Any] = {}
    if path.is_file():
        try:
            # utf-8-sig: the deploy script writes via PS 5.1 Out-File, which adds a BOM
            data = json.loads(path.read_text(encoding="utf-8-sig"))
        except ValueError:
            data = {}
    data.update(updates)
    path.write_text(json.dumps(data, indent=2), encoding="utf-8")
    return path


def _terraform_mcp_client_safe():
    """Terraform MCP is optional — docker may not be running. Return client or None."""
    try:
        from _shared.mcp_clients import terraform_mcp_client

        client = terraform_mcp_client()
        client.start()
        return client
    except Exception as exc:  # noqa: BLE001 — degrade gracefully, template still works
        print(f"[{AGENT_NAME}] terraform MCP unavailable ({exc}); using template only.")
        return None


def run_task(task: str, context: dict[str, Any] | None = None, *, target_app: str | None = None) -> str:
    app = resolve_target_app(target_app, context, env_var="DEVOPS_TARGET_APP")
    ctx = context if context is not None else {"targetApp": app}
    ctx.setdefault("targetApp", app)
    enrich_handoff_context(ctx, include_db_paths=False)

    copied = ensure_deploy_dockerfiles(app)
    manifest = build_deploy_manifest(app, ctx)

    message = (
        f"{task}\n\n"
        f"## Deploy manifest (ground truth)\n```json\n{json.dumps(manifest, indent=2)}\n```\n\n"
        f"## CANONICAL TEMPLATE for infrastructure/environments/dev/{app}/main.tf\n"
        f"```hcl\n{render_tf_root(manifest)}```\n\n"
        "Write this root with devops_write_tf (adjust ONLY if the manifest demands it), "
        "then devops_validate. Remember the workflow in your system prompt."
    )
    if copied:
        message += f"\n\nNote: Dockerfiles were auto-copied from the template: {copied}"

    mcp_client = _terraform_mcp_client_safe()
    tools: list[Any] = [devops_read_file, devops_write_tf, devops_validate]
    try:
        if mcp_client is not None:
            try:
                tools.extend(mcp_client.list_tools_sync())
            except Exception as exc:  # noqa: BLE001
                print(f"[{AGENT_NAME}] terraform MCP list_tools failed ({exc}); continuing.")

        agent = Agent(
            agent_id=AGENT_NAME,
            name=AGENT_NAME,
            description="Generates and validates per-app Terraform deploy roots (ECS Fargate).",
            model=_bedrock_model(),
            system_prompt=DEVOPS_SYS_PROMPT,
            tools=tools,
        )
        result = str(agent(message))
    finally:
        if mcp_client is not None:
            try:
                mcp_client.stop(None, None, None)
            except Exception:  # noqa: BLE001
                pass

    validated = (_tf_root(app) / "main.tf").is_file()
    _merge_handoff(
        app,
        {
            "targetApp": app,
            "tfRoot": f"infrastructure/environments/dev/{app}",
            "manifest": manifest,
            # top-level so derive_extra_env can reuse the same generated secrets
            # on redeploys instead of rotating them
            "extraEnv": manifest.get("extraEnv") or {},
            "tfGeneratedAt": datetime.now(timezone.utc).isoformat(),
            "tfRootPresent": validated,
        },
    )
    return result


def _powershell_exe() -> str:
    """'powershell' (5.1) is what this repo's scripts are tested against on
    Windows; Linux/macOS runners (e.g. GitLab CI) only have 'pwsh' (PowerShell
    Core), if installed at all. Prefer the Windows-native binary so local
    behavior is unchanged; fall back to pwsh for non-Windows runners."""
    for candidate in ("powershell", "pwsh"):
        if shutil.which(candidate):
            return candidate
    raise RuntimeError(
        "No PowerShell found on PATH (tried 'powershell' and 'pwsh'). Install "
        "PowerShell Core (https://aka.ms/powershell) to run "
        "scripts/deploy-target-app.ps1 in this environment."
    )


def run_deploy(app: str, *, plan_only: bool = False, destroy: bool = False) -> int:
    """Invoke the deterministic deploy script (build + push + terraform apply + wait)."""
    script = _REPO_ROOT / "scripts" / "deploy-target-app.ps1"
    cmd = [
        _powershell_exe(),
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        str(script),
        "-Feature",
        app,
    ]
    if plan_only:
        cmd.append("-PlanOnly")
    if destroy:
        cmd.append("-Destroy")

    env = {**os.environ}
    db_url = database_url_from_env()
    if db_url and "TF_VAR_database_url" not in env:
        env["TF_VAR_database_url"] = db_url

    print(f"[{AGENT_NAME}] running deploy script: {' '.join(cmd[-4:])}")
    proc = subprocess.run(cmd, cwd=_REPO_ROOT, env=env)
    return proc.returncode


def build_devops_agent() -> Agent:
    """Tooled devops agent — used by serve_a2a and the AgentCore bundle."""
    return Agent(
        agent_id=AGENT_NAME,
        name=AGENT_NAME,
        description="Generates and validates per-app Terraform deploy roots (ECS Fargate).",
        model=_bedrock_model(),
        system_prompt=DEVOPS_SYS_PROMPT,
        tools=[devops_read_file, devops_write_tf, devops_validate],
    )


def serve_a2a(host: str = "127.0.0.1", port: int = A2A_PORT) -> None:
    agent = build_devops_agent()
    skills = [
        AgentSkill(
            id="delivery",
            name="delivery",
            description="Terraform deploy roots + ECS Fargate deploys for target-apps.",
            tags=["devops", "terraform", "ecs", "deploy"],
        )
    ]
    A2AServer(agent, host=host, port=port, skills=skills).serve()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="DevOps agent — Terraform deploy root generation + AWS deploy"
    )
    parser.add_argument(
        "--task",
        default="Generate and validate the Terraform deploy root for the target app.",
    )
    parser.add_argument("--target-app", help="Feature slug")
    parser.add_argument(
        "--no-auto-context",
        action="store_true",
        help="Do not auto-load agents/pipeline/<app>.context.json",
    )
    load_context_extra(parser)
    parser.add_argument(
        "--deploy",
        action="store_true",
        help="After generating+validating, run scripts/deploy-target-app.ps1 (auto-apply).",
    )
    parser.add_argument(
        "--plan-only",
        action="store_true",
        help="With --deploy: terraform plan only, no changes.",
    )
    parser.add_argument(
        "--destroy",
        action="store_true",
        help="Tear down the app's AWS resources (skips generation).",
    )
    parser.add_argument("--serve-a2a", action="store_true")
    parser.add_argument("--port", type=int, default=A2A_PORT)
    parser.add_argument("--host", default="127.0.0.1")
    args = parser.parse_args()

    if args.serve_a2a:
        serve_a2a(host=args.host, port=args.port)
        return

    try:
        ctx, target = resolve_cli_context(
            args.target_app,
            parse_context_args(args),
            no_auto_context=args.no_auto_context,
            env_var="DEVOPS_TARGET_APP",
        )
    except TargetAppRequiredError as exc:
        parser.error(str(exc))

    _ensure_pipeline_run_id_from_marker(target, ctx)

    if args.destroy:
        raise SystemExit(run_deploy(target, destroy=True))

    summary = run_task(args.task, ctx, target_app=target)
    print("\n" + "=" * 60)
    print(summary)

    if args.deploy or args.plan_only:
        rc = run_deploy(target, plan_only=args.plan_only)
        handoff = _PIPELINE_DIR / f"{target}.devops-handoff.json"
        data = (
            json.loads(handoff.read_text(encoding="utf-8-sig"))
            if handoff.is_file()
            else None
        )

        # Record handoff + run status even on failure — this stage may run
        # standalone (e.g. GitLab CI), outside the orchestrator that normally
        # does this after every other agent's step. Mirrors gitlab-agent's own
        # put_handoff() call, gated the same way (put_handoff builds an S3 URI
        # unconditionally, so it isn't safe to call outside S3 mode).
        run_id = resolve_run_id(ctx)
        if is_s3_store():
            if run_id:
                if data:
                    put_handoff(run_id, "devops", data)
                update_pipeline_run(
                    run_id,
                    status="completed" if rc == 0 else "failed",
                    last_agent=AGENT_NAME,
                )
            else:
                print(
                    f"[{AGENT_NAME}] WARN: ARTIFACT_STORE=s3 but no PIPELINE_RUN_ID "
                    f"(checked marker paths under target-apps/{target}/.sdlc and .sdlc/) "
                    "— frontend will not get appUrl for this deploy",
                    file=sys.stderr,
                )

        if rc != 0:
            raise SystemExit(rc)
        if data and data.get("appUrl"):
            print(f"\n[{AGENT_NAME}] Live UI: {data['appUrl']}")


if __name__ == "__main__":
    main()
