-- 000_legacy_schema_reset.sql
-- Drop any stale change_request_hub schema from earlier pipeline runs so the
-- numbered migrations always apply to a clean slate (same convention as
-- audit-finding-tracker). Dev-only: this schema is fully regenerated by 001-011.

DROP SCHEMA IF EXISTS change_request_hub CASCADE;
